"""add_internal_reference_to_orders

Revision ID: 1ecb90e9b421
Revises: c5354518bf63
Create Date: 2025-10-24 13:04:22.729025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecb90e9b421'
down_revision: Union[str, None] = 'c5354518bf63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('orders')]
    
    if 'internal_reference' not in columns:
        op.add_column('orders', sa.Column('internal_reference', sa.String(12), nullable=True, index=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('orders')]
    
    if 'internal_reference' in columns:
        op.drop_column('orders', 'internal_reference')
    # ### end Alembic commands ###
