"""ricrea_tabelle_configurazioni

Revision ID: 202ade727e8a
Revises: 59eb2b816c8d
Create Date: 2025-10-23 16:27:16.394301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202ade727e8a'
down_revision: Union[str, None] = '59eb2b816c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brt_configurations',
    sa.Column('id_brt_config', sa.Integer(), nullable=False),
    sa.Column('id_carrier_api', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('api_user', sa.String(length=100), nullable=True),
    sa.Column('api_password', sa.String(length=255), nullable=True),
    sa.Column('departure_line', sa.Integer(), nullable=True),
    sa.Column('client_code', sa.Integer(), nullable=True),
    sa.Column('departure_branch', sa.Integer(), nullable=True),
    sa.Column('rate_code', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('default_weight', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('collection_mode', sa.String(length=50), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('label_format', sa.String(length=50), nullable=True),
    sa.Column('customer_notification', sa.String(length=50), nullable=True),
    sa.Column('tracking_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_carrier_api'], ['carriers_api.id_carrier_api'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_brt_config')
    )
    op.create_index(op.f('ix_brt_configurations_id_brt_config'), 'brt_configurations', ['id_brt_config'], unique=False)
    op.create_index(op.f('ix_brt_configurations_id_carrier_api'), 'brt_configurations', ['id_carrier_api'], unique=True)
    op.create_table('dhl_configurations',
    sa.Column('id_dhl_config', sa.Integer(), nullable=False),
    sa.Column('id_carrier_api', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shipper_account_number', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('reference_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('default_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('package_height', sa.Integer(), nullable=True),
    sa.Column('package_width', sa.Integer(), nullable=True),
    sa.Column('package_depth', sa.Integer(), nullable=True),
    sa.Column('goods_description', sa.Text(), nullable=True),
    sa.Column('label_format', sa.Enum('PDF', 'ZPL', name='labelformatenum'), nullable=True),
    sa.Column('unit_of_measure', sa.Enum('METRIC', 'IMPERIAL', name='unitofmeasureenum'), nullable=True),
    sa.Column('default_is_customs_declarable', sa.Boolean(), nullable=True),
    sa.Column('default_incoterm', sa.String(length=3), nullable=True),
    sa.Column('duties_account_number', sa.String(length=255), nullable=True),
    sa.Column('payer_account_number', sa.String(length=255), nullable=True),
    sa.Column('province_code', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=255), nullable=True),
    sa.Column('pickup_is_requested', sa.Boolean(), nullable=True),
    sa.Column('pickup_close_time', sa.String(length=5), nullable=True),
    sa.Column('pickup_location', sa.String(length=255), nullable=True),
    sa.Column('default_product_code_domestic', sa.String(length=100), nullable=True),
    sa.Column('default_product_code_international', sa.String(length=100), nullable=True),
    sa.Column('cod_enabled', sa.Boolean(), nullable=True),
    sa.Column('cod_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['id_carrier_api'], ['carriers_api.id_carrier_api'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dhl_config')
    )
    op.create_index(op.f('ix_dhl_configurations_id_carrier_api'), 'dhl_configurations', ['id_carrier_api'], unique=True)
    op.create_index(op.f('ix_dhl_configurations_id_dhl_config'), 'dhl_configurations', ['id_dhl_config'], unique=False)
    op.create_table('fedex_configurations',
    sa.Column('id_fedex_config', sa.Integer(), nullable=False),
    sa.Column('id_carrier_api', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_or_province_code', sa.String(length=10), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('package_height', sa.Integer(), nullable=True),
    sa.Column('package_width', sa.Integer(), nullable=True),
    sa.Column('package_depth', sa.Integer(), nullable=True),
    sa.Column('default_weight', sa.Integer(), nullable=True),
    sa.Column('sandbox', sa.String(length=10), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('packaging_type', sa.String(length=100), nullable=True),
    sa.Column('pickup_type', sa.String(length=100), nullable=True),
    sa.Column('customs_charges', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('notes_field', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_carrier_api'], ['carriers_api.id_carrier_api'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_fedex_config')
    )
    op.create_index(op.f('ix_fedex_configurations_id_carrier_api'), 'fedex_configurations', ['id_carrier_api'], unique=True)
    op.create_index(op.f('ix_fedex_configurations_id_fedex_config'), 'fedex_configurations', ['id_fedex_config'], unique=False)
    op.create_table('shipments_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_shipping', sa.Integer(), nullable=False),
    sa.Column('id_shipping_state', sa.Integer(), nullable=False),
    sa.Column('id_shipping_state_previous', sa.Integer(), nullable=True),
    sa.Column('tracking_event_code', sa.String(length=10), nullable=True),
    sa.Column('tracking_event_description', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'DHL_TRACKING', 'API_UPDATE', name='sourceenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_shipping'], ['shipments.id_shipping'], ),
    sa.ForeignKeyConstraint(['id_shipping_state'], ['shipping_state.id_shipping_state'], ),
    sa.ForeignKeyConstraint(['id_shipping_state_previous'], ['shipping_state.id_shipping_state'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_history_changed_at'), 'shipments_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_shipments_history_id'), 'shipments_history', ['id'], unique=False)
    op.create_table('shipment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_carrier_api', sa.Integer(), nullable=False),
    sa.Column('awb', sa.String(length=50), nullable=True),
    sa.Column('message_reference', sa.String(length=100), nullable=True),
    sa.Column('request_json_redacted', sa.Text(), nullable=True),
    sa.Column('response_json_redacted', sa.Text(), nullable=True),
    sa.Column('environment', sa.Enum('SANDBOX', 'PRODUCTION', name='environmentenum'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrier_api'], ['carriers_api.id_carrier_api'], ),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_requests_awb'), 'shipment_requests', ['awb'], unique=False)
    op.create_index(op.f('ix_shipment_requests_expires_at'), 'shipment_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shipment_requests_id'), 'shipment_requests', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_requests_message_reference'), 'shipment_requests', ['message_reference'], unique=True)
    op.create_table('shipment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awb', sa.String(length=50), nullable=False),
    sa.Column('id_shipment_request', sa.Integer(), nullable=True),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_shipment_request'], ['shipment_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_shipment_documents_awb'), 'shipment_documents', ['awb'], unique=False)
    op.create_index(op.f('ix_shipment_documents_created_at'), 'shipment_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipment_documents_expires_at'), 'shipment_documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shipment_documents_id'), 'shipment_documents', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_documents_sha256_hash'), 'shipment_documents', ['sha256_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_documents_sha256_hash'), table_name='shipment_documents')
    op.drop_index(op.f('ix_shipment_documents_id'), table_name='shipment_documents')
    op.drop_index(op.f('ix_shipment_documents_expires_at'), table_name='shipment_documents')
    op.drop_index(op.f('ix_shipment_documents_created_at'), table_name='shipment_documents')
    op.drop_index(op.f('ix_shipment_documents_awb'), table_name='shipment_documents')
    op.drop_table('shipment_documents')
    op.drop_index(op.f('ix_shipment_requests_message_reference'), table_name='shipment_requests')
    op.drop_index(op.f('ix_shipment_requests_id'), table_name='shipment_requests')
    op.drop_index(op.f('ix_shipment_requests_expires_at'), table_name='shipment_requests')
    op.drop_index(op.f('ix_shipment_requests_awb'), table_name='shipment_requests')
    op.drop_table('shipment_requests')
    op.drop_index(op.f('ix_shipments_history_id'), table_name='shipments_history')
    op.drop_index(op.f('ix_shipments_history_changed_at'), table_name='shipments_history')
    op.drop_table('shipments_history')
    op.drop_index(op.f('ix_fedex_configurations_id_fedex_config'), table_name='fedex_configurations')
    op.drop_index(op.f('ix_fedex_configurations_id_carrier_api'), table_name='fedex_configurations')
    op.drop_table('fedex_configurations')
    op.drop_index(op.f('ix_dhl_configurations_id_dhl_config'), table_name='dhl_configurations')
    op.drop_index(op.f('ix_dhl_configurations_id_carrier_api'), table_name='dhl_configurations')
    op.drop_table('dhl_configurations')
    op.drop_index(op.f('ix_brt_configurations_id_carrier_api'), table_name='brt_configurations')
    op.drop_index(op.f('ix_brt_configurations_id_brt_config'), table_name='brt_configurations')
    op.drop_table('brt_configurations')
    # ### end Alembic commands ###
