"""update_carrier_api

Revision ID: 35394d53e759
Revises: c0684086166d
Create Date: 2025-10-31 16:40:12.320147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35394d53e759'
down_revision: Union[str, None] = 'c0684086166d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # Verifica che la tabella carriers_api esista
    if 'carriers_api' not in inspector.get_table_names():
        print("⚠️  carriers_api table does not exist")
        return
    
    columns = [col['name'] for col in inspector.get_columns('carriers_api')]
    
    # Rimuovi colonne solo se esistono
    if 'api_password' in columns:
        op.drop_column('carriers_api', 'api_password')
        print("✅ Removed api_password column from carriers_api")
    
    if 'api_username' in columns:
        op.drop_column('carriers_api', 'api_username')
        print("✅ Removed api_username column from carriers_api")
    
    if 'sandbox_api_username' in columns:
        op.drop_column('carriers_api', 'sandbox_api_username')
        print("✅ Removed sandbox_api_username column from carriers_api")
    
    if 'sandbox_api_password' in columns:
        op.drop_column('carriers_api', 'sandbox_api_password')
        print("✅ Removed sandbox_api_password column from carriers_api")
    
    # Non modificare gli indici perché sono utilizzati da foreign keys
    # Gli indici verranno gestiti automaticamente da MySQL se necessario
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # Verifica che la tabella carriers_api esista
    if 'carriers_api' not in inspector.get_table_names():
        print("⚠️  carriers_api table does not exist")
        return
    
    columns = [col['name'] for col in inspector.get_columns('carriers_api')]
    
    # Aggiungi colonne solo se non esistono
    if 'sandbox_api_password' not in columns:
        op.add_column('carriers_api', sa.Column('sandbox_api_password', mysql.VARCHAR(length=255), nullable=True))
        print("✅ Added sandbox_api_password column to carriers_api")
    
    if 'sandbox_api_username' not in columns:
        op.add_column('carriers_api', sa.Column('sandbox_api_username', mysql.VARCHAR(length=255), nullable=True))
        print("✅ Added sandbox_api_username column to carriers_api")
    
    if 'api_username' not in columns:
        op.add_column('carriers_api', sa.Column('api_username', mysql.VARCHAR(length=255), nullable=True))
        print("✅ Added api_username column to carriers_api")
    
    if 'api_password' not in columns:
        op.add_column('carriers_api', sa.Column('api_password', mysql.VARCHAR(length=255), nullable=True))
        print("✅ Added api_password column to carriers_api")
    # ### end Alembic commands ###
