"""Move DHL client_id and client_secret from carriers_api to dhl_configurations

Revision ID: 43a057efad01
Revises: dfcddd483a3f
Create Date: 2025-10-24 09:05:05.938137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43a057efad01'
down_revision: Union[str, None] = 'dfcddd483a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carriers_api', 'dhl_client_secret')
    op.drop_column('carriers_api', 'dhl_sandbox_client_id')
    op.drop_column('carriers_api', 'dhl_client_id')
    op.drop_column('carriers_api', 'dhl_sandbox_client_secret')
    op.add_column('dhl_configurations', sa.Column('client_id', sa.String(length=255), nullable=True))
    op.add_column('dhl_configurations', sa.Column('client_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dhl_configurations', 'client_secret')
    op.drop_column('dhl_configurations', 'client_id')
    op.add_column('carriers_api', sa.Column('dhl_sandbox_client_secret', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('carriers_api', sa.Column('dhl_client_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('carriers_api', sa.Column('dhl_sandbox_client_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('carriers_api', sa.Column('dhl_client_secret', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
