"""ricrea_tabelle_configurazioni

Revision ID: 59eb2b816c8d
Revises: ae19ac46be2d
Create Date: 2025-10-23 16:23:26.147404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59eb2b816c8d'
down_revision: Union[str, None] = 'ae19ac46be2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
