"""remove_reference_from_shipments

Revision ID: 9f3eb3459e01
Revises: 1ecb90e9b421
Create Date: 2025-10-24 13:05:59.201811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3eb3459e01'
down_revision: Union[str, None] = '1ecb90e9b421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('shipments')]
    
    if 'reference' in columns:
        op.drop_column('shipments', 'reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column doesn't exist before adding it back
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('shipments')]
    
    if 'reference' not in columns:
        op.add_column('shipments', sa.Column('reference', sa.String(50), nullable=True, index=True))
    # ### end Alembic commands ###
