"""modifica_elimina_colonne

Revision ID: ae19ac46be2d
Revises: 5c44d2400e1d
Create Date: 2025-10-23 16:19:01.604837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae19ac46be2d'
down_revision: Union[str, None] = '5c44d2400e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    existing_tables = sa.inspect(conn).get_table_names()

    # Drop tables (this automatically drops indexes and constraints).
    # Guardato per bootstrap da zero: alcune di queste tabelle non sono mai
    # state create da nessuna migration precedente (nascevano da create_all()).
    for table_name in (
        'shipment_documents', 'shipments_history', 'shipment_requests',
        'brt_configurations', 'dhl_configurations', 'fedex_configurations',
    ):
        if table_name in existing_tables:
            op.drop_table(table_name)

    # Modify carriers_api table
    op.alter_column('carriers_api', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.create_index(op.f('ix_carriers_api_carrier_type'), 'carriers_api', ['carrier_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carriers_api_carrier_type'), table_name='carriers_api')
    op.alter_column('carriers_api', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    
    # Recreate tables in reverse order
    op.create_table('shipment_requests',
    sa.Column('id_shipment_request', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carrier_api_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awb', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message_reference', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('environment', mysql.ENUM('SANDBOX', 'PRODUCTION'), nullable=False),
    sa.Column('request_payload', mysql.JSON(), nullable=True),
    sa.Column('response_payload', mysql.JSON(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_shipment_request'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('message_reference', 'shipment_requests', ['message_reference'], unique=True)
    
    op.create_table('shipment_documents',
    sa.Column('id_shipment_document', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shipment_request_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_request_id'], ['shipment_requests.id_shipment_request'], name='shipment_documents_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_shipment_document'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    op.create_table('shipments_history',
    sa.Column('id_shipment_history', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awb', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('carrier', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tracking_data', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_shipment_history'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    op.create_table('fedex_configurations',
    sa.Column('id_fedex_config', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_carrier_api', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('client_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('client_secret', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('account_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state_or_province_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('postal_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('package_height', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package_width', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package_depth', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default_weight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sandbox', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('service_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('packaging_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pickup_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('customs_charges', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('format', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('notes_field', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_carrier_api'], ['carriers_api.id_carrier_api'], name='fedex_configurations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_fedex_config'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fedex_configurations_id_fedex_config', 'fedex_configurations', ['id_fedex_config'], unique=False)
    op.create_index('ix_fedex_configurations_id_carrier_api', 'fedex_configurations', ['id_carrier_api'], unique=True)
    
    op.create_table('dhl_configurations',
    sa.Column('id_dhl_config', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_carrier_api', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('shipper_account_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('site_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('postal_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('reference_person', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('default_weight', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('package_height', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package_width', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package_depth', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goods_description', mysql.TEXT(), nullable=True),
    sa.Column('label_format', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('print_waybill', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sku_quantity', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('default_product_code_domestic', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('default_product_code_international', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_carrier_api'], ['carriers_api.id_carrier_api'], name='dhl_configurations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dhl_config'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dhl_configurations_id_dhl_config', 'dhl_configurations', ['id_dhl_config'], unique=False)
    op.create_index('ix_dhl_configurations_id_carrier_api', 'dhl_configurations', ['id_carrier_api'], unique=True)
    
    op.create_table('brt_configurations',
    sa.Column('id_brt_config', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_carrier_api', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sender', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('api_user', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('api_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('departure_line', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('departure_branch', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('default_weight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('collection_mode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('network', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('label_format', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('customer_notification', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tracking_type', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_carrier_api'], ['carriers_api.id_carrier_api'], name='brt_configurations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_brt_config'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_brt_configurations_id_carrier_api', 'brt_configurations', ['id_carrier_api'], unique=True)
    op.create_index('ix_brt_configurations_id_brt_config', 'brt_configurations', ['id_brt_config'], unique=False)
    # ### end Alembic commands ###