"""add_order_id_and_carrier_api_id_to_shipment_documents

Revision ID: c5354518bf63
Revises: 7dae0477f452
Create Date: 2025-10-24 11:19:26.736623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5354518bf63'
down_revision: Union[str, None] = '7dae0477f452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist before adding them
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('shipment_documents')]
    
    if 'order_id' not in columns:
        op.add_column('shipment_documents', sa.Column('order_id', sa.Integer(), nullable=True, index=True))
    
    if 'carrier_api_id' not in columns:
        op.add_column('shipment_documents', sa.Column('carrier_api_id', sa.Integer(), nullable=True, index=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before dropping them
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('shipment_documents')]
    
    if 'order_id' in columns:
        op.drop_column('shipment_documents', 'order_id')
    
    if 'carrier_api_id' in columns:
        op.drop_column('shipment_documents', 'carrier_api_id')
    # ### end Alembic commands ###
