"""add_price_quantity_platform_fields

Revision ID: df3e3b3684be
Revises: 35394d53e759
Create Date: 2025-11-03 16:21:35.122260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3e3b3684be'
down_revision: Union[str, None] = '35394d53e759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # Step 1: Check if platform with id=0 exists, if not check for id=1 (PrestaShop)
    result = connection.execute(sa.text("SELECT id_platform FROM platforms WHERE id_platform = 0 LIMIT 1"))
    platform_0 = result.fetchone()
    
    if platform_0:
        default_platform_id = 0
    else:
        # Check for PrestaShop (typically id=1)
        result = connection.execute(sa.text("SELECT MIN(id_platform) as min_id FROM platforms"))
        first_platform_id = result.fetchone()[0]
        
        if first_platform_id is None:
            # No platforms exist, create a default one with id=0
            connection.execute(sa.text("INSERT INTO platforms (id_platform, name, is_default) VALUES (0, 'Internal/App', 1)"))
            default_platform_id = 0
        else:
            # Use the first available platform (typically PrestaShop with id=1)
            default_platform_id = first_platform_id
    
    # Step 2: Check existing columns and add only if they don't exist
    brands_columns = [col['name'] for col in inspector.get_columns('brands')]
    categories_columns = [col['name'] for col in inspector.get_columns('categories')]
    products_columns = [col['name'] for col in inspector.get_columns('products')]
    
    # Add columns as nullable first (only if they don't exist)
    if 'id_platform' not in brands_columns:
        op.add_column('brands', sa.Column('id_platform', sa.Integer(), nullable=True))
    if 'id_platform' not in categories_columns:
        op.add_column('categories', sa.Column('id_platform', sa.Integer(), nullable=True))
    if 'id_platform' not in products_columns:
        op.add_column('products', sa.Column('id_platform', sa.Integer(), nullable=True))
    if 'price_without_tax' not in products_columns:
        op.add_column('products', sa.Column('price_without_tax', sa.Float(), nullable=True))
    if 'quantity' not in products_columns:
        op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    
    # Step 3: Update existing records with default platform ID
    # Update NULL values and also verify all values are valid
    # First, get all valid platform IDs
    result = connection.execute(sa.text("SELECT id_platform FROM platforms"))
    valid_platform_ids = [row[0] for row in result.fetchall()]
    
    if not valid_platform_ids:
        # No platforms exist, create default
        connection.execute(sa.text("INSERT INTO platforms (id_platform, name, is_default) VALUES (0, 'Internal/App', 1)"))
        valid_platform_ids = [0]
        default_platform_id = 0
    
    # Update all NULL or invalid id_platform values
    # For brands
    if 'id_platform' in brands_columns:
        # Update NULL or invalid values
        op.execute(f"UPDATE brands SET id_platform = {default_platform_id} WHERE id_platform IS NULL OR id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")
    else:
        # Column doesn't exist yet, so update NULL only
        op.execute(f"UPDATE brands SET id_platform = {default_platform_id} WHERE id_platform IS NULL")
    
    # For categories
    if 'id_platform' in categories_columns:
        op.execute(f"UPDATE categories SET id_platform = {default_platform_id} WHERE id_platform IS NULL OR id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")
    else:
        op.execute(f"UPDATE categories SET id_platform = {default_platform_id} WHERE id_platform IS NULL")
    
    # For products
    if 'id_platform' in products_columns:
        op.execute(f"UPDATE products SET id_platform = {default_platform_id} WHERE id_platform IS NULL OR id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")
    else:
        op.execute(f"UPDATE products SET id_platform = {default_platform_id} WHERE id_platform IS NULL")
    
    op.execute("UPDATE products SET price_without_tax = 0.0 WHERE price_without_tax IS NULL")
    op.execute("UPDATE products SET quantity = 0 WHERE quantity IS NULL")
    
    # Verify all records have valid platform IDs before proceeding
    # Double-check by counting invalid records
    invalid_brands = connection.execute(sa.text(f"SELECT COUNT(*) FROM brands WHERE id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")).fetchone()[0]
    invalid_categories = connection.execute(sa.text(f"SELECT COUNT(*) FROM categories WHERE id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")).fetchone()[0]
    invalid_products = connection.execute(sa.text(f"SELECT COUNT(*) FROM products WHERE id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")).fetchone()[0]
    
    if invalid_brands > 0 or invalid_categories > 0 or invalid_products > 0:
        # Force update any remaining invalid values
        if invalid_brands > 0:
            op.execute(f"UPDATE brands SET id_platform = {default_platform_id} WHERE id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")
        if invalid_categories > 0:
            op.execute(f"UPDATE categories SET id_platform = {default_platform_id} WHERE id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")
        if invalid_products > 0:
            op.execute(f"UPDATE products SET id_platform = {default_platform_id} WHERE id_platform NOT IN ({','.join(map(str, valid_platform_ids))})")
    
    # Step 4: Make columns NOT NULL (only if they are currently nullable)
    # Get current column info to check nullable status
    brands_platform_col = next((col for col in inspector.get_columns('brands') if col['name'] == 'id_platform'), None)
    categories_platform_col = next((col for col in inspector.get_columns('categories') if col['name'] == 'id_platform'), None)
    products_platform_col = next((col for col in inspector.get_columns('products') if col['name'] == 'id_platform'), None)
    
    if brands_platform_col and brands_platform_col.get('nullable', True):
        op.alter_column(
            'brands',
            'id_platform',
            nullable=False,
            existing_type=sa.Integer(),
        )
    if categories_platform_col and categories_platform_col.get('nullable', True):
        op.alter_column(
            'categories',
            'id_platform',
            nullable=False,
            existing_type=sa.Integer(),
        )
    if products_platform_col and products_platform_col.get('nullable', True):
        op.alter_column(
            'products',
            'id_platform',
            nullable=False,
            existing_type=sa.Integer(),
        )
    
    # Step 5: Create indexes (only if they don't exist)
    indexes = {idx['name']: idx for idx in inspector.get_indexes('brands')}
    if 'ix_brands_id_platform' not in indexes:
        op.create_index(op.f('ix_brands_id_platform'), 'brands', ['id_platform'], unique=False)
    
    indexes = {idx['name']: idx for idx in inspector.get_indexes('categories')}
    if 'ix_categories_id_platform' not in indexes:
        op.create_index(op.f('ix_categories_id_platform'), 'categories', ['id_platform'], unique=False)
    
    indexes = {idx['name']: idx for idx in inspector.get_indexes('products')}
    if 'ix_products_id_platform' not in indexes:
        op.create_index(op.f('ix_products_id_platform'), 'products', ['id_platform'], unique=False)
    
    # Step 6: Add foreign key constraints (only if they don't exist)
    # Check existing foreign keys
    fks_brands = {fk['name']: fk for fk in inspector.get_foreign_keys('brands')}
    fks_categories = {fk['name']: fk for fk in inspector.get_foreign_keys('categories')}
    fks_products = {fk['name']: fk for fk in inspector.get_foreign_keys('products')}
    
    # Check if FK to platforms.id_platform already exists
    brands_has_fk = any(fk['constrained_columns'] == ['id_platform'] and 
                       fk['referred_table'] == 'platforms' 
                       for fk in fks_brands.values())
    categories_has_fk = any(fk['constrained_columns'] == ['id_platform'] and 
                            fk['referred_table'] == 'platforms' 
                            for fk in fks_categories.values())
    products_has_fk = any(fk['constrained_columns'] == ['id_platform'] and 
                         fk['referred_table'] == 'platforms' 
                         for fk in fks_products.values())
    
    if not brands_has_fk:
        op.create_foreign_key('fk_brands_platform', 'brands', 'platforms', ['id_platform'], ['id_platform'])
    if not categories_has_fk:
        op.create_foreign_key('fk_categories_platform', 'categories', 'platforms', ['id_platform'], ['id_platform'])
    if not products_has_fk:
        op.create_foreign_key('fk_products_platform', 'products', 'platforms', ['id_platform'], ['id_platform'])
    
    # Other index updates
    order_packages_indexes = {idx['name'] for idx in inspector.get_indexes('order_packages')}
    if 'ix_order_packages_id_order_document' not in order_packages_indexes:
        if 'idx_order_packages_id_order_document' in order_packages_indexes:
            op.execute("ALTER TABLE order_packages RENAME INDEX idx_order_packages_id_order_document TO ix_order_packages_id_order_document")
        else:
            op.create_index(op.f('ix_order_packages_id_order_document'), 'order_packages', ['id_order_document'], unique=False)

    orders_document_indexes = {idx['name'] for idx in inspector.get_indexes('orders_document')}
    if 'ix_orders_document_id_payment' not in orders_document_indexes:
        if 'idx_orders_document_id_payment' in orders_document_indexes:
            op.execute("ALTER TABLE orders_document RENAME INDEX idx_orders_document_id_payment TO ix_orders_document_id_payment")
        else:
            op.create_index(op.f('ix_orders_document_id_payment'), 'orders_document', ['id_payment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_id_platform'), table_name='products')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'price_without_tax')
    op.drop_column('products', 'id_platform')
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    orders_document_indexes = {idx['name'] for idx in inspector.get_indexes('orders_document')}
    if 'ix_orders_document_id_payment' in orders_document_indexes:
        op.execute("ALTER TABLE orders_document RENAME INDEX ix_orders_document_id_payment TO idx_orders_document_id_payment")
    elif 'idx_orders_document_id_payment' not in orders_document_indexes:
        op.create_index('idx_orders_document_id_payment', 'orders_document', ['id_payment'], unique=False)

    order_packages_indexes = {idx['name'] for idx in inspector.get_indexes('order_packages')}
    if 'ix_order_packages_id_order_document' in order_packages_indexes:
        op.execute("ALTER TABLE order_packages RENAME INDEX ix_order_packages_id_order_document TO idx_order_packages_id_order_document")
    elif 'idx_order_packages_id_order_document' not in order_packages_indexes:
        op.create_index('idx_order_packages_id_order_document', 'order_packages', ['id_order_document'], unique=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_id_platform'), table_name='categories')
    op.drop_column('categories', 'id_platform')
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_index(op.f('ix_brands_id_platform'), table_name='brands')
    op.drop_column('brands', 'id_platform')
    # ### end Alembic commands ###
