"""Add DHL client_id and client_secret fields to carriers_api

Revision ID: dfcddd483a3f
Revises: 202ade727e8a
Create Date: 2025-10-24 09:02:17.155507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcddd483a3f'
down_revision: Union[str, None] = '202ade727e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carriers_api', sa.Column('dhl_client_id', sa.String(length=255), nullable=True))
    op.add_column('carriers_api', sa.Column('dhl_client_secret', sa.String(length=255), nullable=True))
    op.add_column('carriers_api', sa.Column('dhl_sandbox_client_id', sa.String(length=255), nullable=True))
    op.add_column('carriers_api', sa.Column('dhl_sandbox_client_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carriers_api', 'dhl_sandbox_client_secret')
    op.drop_column('carriers_api', 'dhl_sandbox_client_id')
    op.drop_column('carriers_api', 'dhl_client_secret')
    op.drop_column('carriers_api', 'dhl_client_id')
    # ### end Alembic commands ###
