"""add_rda_quantity_to_order_details

Revision ID: f49ad02321c1
Revises: 77a97ae89e14
Create Date: 2025-12-09 15:10:14.126142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f49ad02321c1'
down_revision: Union[str, None] = '77a97ae89e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Aggiungi solo il campo rda_quantity a order_details
    op.add_column('order_details', sa.Column('rda_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rimuovi solo il campo rda_quantity da order_details
    op.drop_column('order_details', 'rda_quantity')
    # ### end Alembic commands ###
