"""Add length column to order_packages with default value 10

Revision ID: fbb5d0c595ee
Revises: 43a057efad01
Create Date: 2025-10-24 09:33:07.723553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb5d0c595ee'
down_revision: Union[str, None] = '43a057efad01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('order_packages')]
    
    if 'length' not in columns:
        op.add_column('order_packages', sa.Column('length', sa.Float(), nullable=True))
    
    # Set default value 10 for existing records that have NULL length
    op.execute("UPDATE order_packages SET length = 10.0 WHERE length IS NULL")
    
    # Make column NOT NULL after setting default values
    op.alter_column('order_packages', 'length', 
                    existing_type=sa.Float(), 
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('order_packages')]
    
    if 'length' in columns:
        op.drop_column('order_packages', 'length')
    # ### end Alembic commands ###
